[tool.poetry]
name = "django-bootstrap-quick-start"
version = "0.1.0"
description = "A Django boilerplate to start your projects faster."
authors = ["Brylie Christopher Oxley <brylie@amble.fi>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
Django = "^4.0"
crispy-bootstrap5 = "^0.6"
django-environ = "^0.8.1"
psycopg2-binary = "^2.9.3"
whitenoise = {extras = ["brotli"], version = "^5.3.0"}

[tool.poetry.dev-dependencies]
black = "^21.12b0"
flake8 = "^4.0.1"
isort = "^5.10.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
